# Generated by Django 3.2 on 2021-04-12 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_neighborhood_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='business', to='main.neighborhood'),
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='main.profile'),
        ),
    ]
